### ISSUE TITLE
Chybí CoC

### ISSUE THREAD

**Issue by RisaI** [m93a/mpf2-ukoly#2]
Ahoj,

rád bych upozornil na absenci CoC v tomto projektu. Pro vývoj je absolutně imperativní, aby každý měl právo vyjádřit svůj názor a mohl kontribuovat do projektu bez ohledu na jeho pohlaví, orientaci, politickou příslušnost a hlavně znalost oboru. Arbitrární požadavek na znalost matematiky a zkušenost se sázením textu v LaTeXu může odradit potenciální nové vývojáře od projektu. Toto není přípustné a v budoucnu to přinese mnoho problémů s udržitelností projektu. Doufám, že budete tolerantní a CoC do projektu vložíte. Díky.

**Comment by cshaa** [comment]
Tvojí mámě chybí coc.
